name: End to End Tests

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout from project
      uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v2
    - name: Clear install dependencies
      run: npm ci 
    - name: Test execution
      run: npm run cy:run
